version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - devops

  database:
    image: mysql:latest
    container_name: database_chat
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'devops'
      MYSQL_DATABASE: 'livechatdb'
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: 'devops'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - devops

networks:
  devops:
    external: true
